import type { MapLayout } from './types';

export const fishingVillageLayout: MapLayout = {
    mapId: 'fishing-village',
    continent: 'CONTINENT · COASTAL',
    region: 'Fishing Village',
    regionProgress: 'Map i of ii · 24 paths remain',
    nodes: [
        // Spine nodes (fv-1..fv-10) - aligned with engine source edges
        {
            id: 'fv-1',
            x: 60,
            y: 360,
            label: 'Hovel',
            type: 'rest',
            connectedNodes: ['fv-2', 'fv-11'],
            description: 'Your salt-scoured hovel. The hearth still gutters.',
        },
        {
            id: 'fv-2',
            x: 140,
            y: 320,
            label: 'Crossing',
            type: 'gather',
            connectedNodes: ['fv-3', 'fv-12'],
            description: 'The plank crossing. Gulls scream over the rocks.',
        },
        {
            id: 'fv-3',
            x: 180,
            y: 280,
            label: 'Hanged Wood',
            type: 'encounter',
            connectedNodes: ['fv-4', 'fv-13', 'fv-16'],
            description: 'A copse where the fishers hang their drowned dead.',
        },
        {
            id: 'fv-4',
            x: 180,
            y: 240,
            label: 'Drowned Shrine',
            type: 'treasure',
            connectedNodes: ['fv-5', 'fv-17'],
            description: 'A half-sunk shrine. Old coin gleams beneath the silt.',
        },
        {
            id: 'fv-5',
            x: 180,
            y: 200,
            label: 'Black Cairn',
            type: 'boss',
            connectedNodes: ['fv-6', 'fv-18'],
            description: 'A cairn of black river-stones. Something watches.',
        },
        {
            id: 'fv-6',
            x: 180,
            y: 160,
            label: 'Ash Mire',
            type: 'quest',
            connectedNodes: ['fv-7'],
            description: 'The mire where the boy-priest told you to look.',
        },
        {
            id: 'fv-7',
            x: 180,
            y: 120,
            label: 'Old Pier',
            type: 'gather',
            connectedNodes: ['fv-8', 'fv-21'],
            description: 'A pier half-eaten by tides. Crabs in the pilings.',
        },
        {
            id: 'fv-8',
            x: 180,
            y: 80,
            label: 'Bone Reach',
            type: 'encounter',
            connectedNodes: ['fv-9', 'fv-22'],
            description: 'A reach of bleached driftwood and bleached bones.',
        },
        {
            id: 'fv-9',
            x: 180,
            y: 40,
            label: 'Tavern',
            type: 'rest',
            connectedNodes: ['fv-10'],
            description: 'A tavern. Stale ale and stale prayer.',
        },
        {
            id: 'fv-10',
            x: 180,
            y: 10,
            label: 'Gate',
            type: 'boss',
            connectedNodes: [],
            description: 'A door you do not yet have the right to open.',
        },

        // Harbor district (fv-11..fv-15) - positioned east of spine
        {
            id: 'fv-11',
            x: 20,
            y: 340,
            label: 'Dock',
            type: 'gather',
            connectedNodes: ['fv-1', 'fv-12', 'fv-14'],
            description: 'Fishing boats bob against the rotting pier.',
        },
        {
            id: 'fv-12',
            x: 60,
            y: 300,
            label: 'Market',
            type: 'rest',
            connectedNodes: ['fv-2', 'fv-11', 'fv-13'],
            description: 'Salt-fish and rusty tools spread on weathered planks.',
        },
        {
            id: 'fv-13',
            x: 100,
            y: 260,
            label: 'Harbor Gate',
            type: 'treasure',
            connectedNodes: ['fv-3', 'fv-12'],
            description: 'Iron gates green with sea-rust. Something gleams within.',
        },
        {
            id: 'fv-14',
            x: 20,
            y: 280,
            label: 'Tide Pool',
            type: 'encounter',
            connectedNodes: ['fv-11', 'fv-15'],
            description: 'Pools carved by the tide. Eyes watch from the depths.',
        },
        {
            id: 'fv-15',
            x: 20,
            y: 240,
            label: 'Sea Cave',
            type: 'quest',
            connectedNodes: ['fv-14'],
            description: 'A cave that breathes with the tide. Old songs echo within.',
        },

        // Inland district (fv-16..fv-20) - positioned west of spine
        {
            id: 'fv-16',
            x: 260,
            y: 260,
            label: 'Chapel',
            type: 'rest',
            connectedNodes: ['fv-3', 'fv-17'],
            description: 'A chapel of bleached coral. Prayer-bones hang from hooks.',
        },
        {
            id: 'fv-17',
            x: 280,
            y: 220,
            label: 'Crossroads',
            type: 'gather',
            connectedNodes: ['fv-4', 'fv-16', 'fv-18', 'fv-19'],
            description: 'Four paths meet. Signposts point to forgotten places.',
        },
        {
            id: 'fv-18',
            x: 260,
            y: 180,
            label: 'Stone Circle',
            type: 'encounter',
            connectedNodes: ['fv-5', 'fv-17', 'fv-19'],
            description: 'Standing stones worn smooth by salt winds.',
        },
        {
            id: 'fv-19',
            x: 320,
            y: 200,
            label: 'Ancient Well',
            type: 'treasure',
            connectedNodes: ['fv-17', 'fv-18', 'fv-20'],
            description: 'A well that goes deeper than memory. Coins shine below.',
        },
        {
            id: 'fv-20',
            x: 340,
            y: 160,
            label: 'Hermit Hut',
            type: 'quest',
            connectedNodes: ['fv-19'],
            description: 'A hermit dwells here. Their eyes hold old secrets.',
        },

        // Cliff district (fv-21..fv-25) - positioned east, upper
        {
            id: 'fv-21',
            x: 280,
            y: 100,
            label: 'Cliff Path',
            type: 'gather',
            connectedNodes: ['fv-7', 'fv-22', 'fv-24'],
            description: 'A narrow path carved into the cliff face.',
        },
        {
            id: 'fv-22',
            x: 260,
            y: 60,
            label: 'Eagles Nest',
            type: 'encounter',
            connectedNodes: ['fv-8', 'fv-21', 'fv-23'],
            description: 'An abandoned eyrie. Bones litter the rocky ledge.',
        },
        {
            id: 'fv-23',
            x: 300,
            y: 40,
            label: 'Wind Shrine',
            type: 'rest',
            connectedNodes: ['fv-22', 'fv-24'],
            description: 'A shrine to the four winds. Prayer flags snap in the gale.',
        },
        {
            id: 'fv-24',
            x: 320,
            y: 80,
            label: 'Peak View',
            type: 'treasure',
            connectedNodes: ['fv-21', 'fv-23', 'fv-25'],
            description: 'The highest point. All the village spreads below.',
        },
        {
            id: 'fv-25',
            x: 340,
            y: 40,
            label: 'Lighthouse',
            type: 'boss',
            connectedNodes: ['fv-24'],
            description: 'A lighthouse dark for decades. Something stirs within.',
        },
    ],
};
