import type { MapLayout } from './types';

export const fishingVillageLayout: MapLayout = {
    mapId: 'fishing-village',
    continent: 'CONTINENT · COASTAL',
    region: 'Fishing Village',
    regionProgress: 'Map i of ii · 9 paths remain',
    nodes: [
        {
            id: 'fv-1',
            x: 60,
            y: 360,
            label: 'Hovel',
            type: 'rest',
            connectedNodes: ['fv-2'],
            description: 'Your salt-scoured hovel. The hearth still gutters.',
        },
        {
            id: 'fv-2',
            x: 140,
            y: 310,
            label: 'Crossing',
            type: 'gather',
            connectedNodes: ['fv-3', 'fv-4'],
            description: 'The plank crossing. Gulls scream over the rocks.',
        },
        {
            id: 'fv-3',
            x: 230,
            y: 270,
            label: 'Hanged Wood',
            type: 'encounter',
            connectedNodes: ['fv-5'],
            description: 'A copse where the fishers hang their drowned dead.',
        },
        {
            id: 'fv-4',
            x: 90,
            y: 220,
            label: 'Drowned Shrine',
            type: 'treasure',
            connectedNodes: ['fv-5', 'fv-6'],
            description: 'A half-sunk shrine. Old coin gleams beneath the silt.',
        },
        {
            id: 'fv-5',
            x: 200,
            y: 170,
            label: 'Black Cairn',
            type: 'boss',
            connectedNodes: ['fv-8'],
            description: 'A cairn of black river-stones. Something watches.',
        },
        {
            id: 'fv-6',
            x: 60,
            y: 140,
            label: 'Ash Mire',
            type: 'quest',
            connectedNodes: ['fv-7'],
            description: 'The mire where the boy-priest told you to look.',
        },
        {
            id: 'fv-7',
            x: 130,
            y: 90,
            label: 'Old Pier',
            type: 'gather',
            connectedNodes: ['fv-9'],
            description: 'A pier half-eaten by tides. Crabs in the pilings.',
        },
        {
            id: 'fv-8',
            x: 280,
            y: 120,
            label: 'Bone Reach',
            type: 'encounter',
            connectedNodes: ['fv-10'],
            description: 'A reach of bleached driftwood and bleached bones.',
        },
        {
            id: 'fv-9',
            x: 200,
            y: 50,
            label: 'Tavern',
            type: 'rest',
            connectedNodes: [],
            description: 'A tavern. Stale ale and stale prayer.',
        },
        {
            id: 'fv-10',
            x: 310,
            y: 50,
            label: '???',
            type: 'boss',
            connectedNodes: [],
            description: 'A door you do not yet have the right to open.',
        },
    ],
};
