import type { MapLayout } from './types';

export const northernForestLayout: MapLayout = {
    mapId: 'northern-forest',
    continent: 'CONTINENT · COASTAL',
    region: 'Northern Forest',
    regionProgress: 'Map ii of ii · 9 paths remain',
    nodes: [
        {
            id: 'nf-1',
            x: 60,
            y: 360,
            label: 'Forest Edge',
            type: 'rest',
            connectedNodes: ['nf-2', 'nf-3'],
            description: 'Where the pines first taste the salt wind.',
        },
        {
            id: 'nf-2',
            x: 140,
            y: 300,
            label: 'Foxglove Hollow',
            type: 'gather',
            connectedNodes: ['nf-4'],
            description: 'A hollow thick with foxglove and adder-tongue.',
        },
        {
            id: 'nf-3',
            x: 220,
            y: 320,
            label: 'Hangman’s Oak',
            type: 'encounter',
            connectedNodes: ['nf-5'],
            description: 'An old oak. Old rope still bites into its bark.',
        },
        {
            id: 'nf-4',
            x: 80,
            y: 220,
            label: 'Iron Spring',
            type: 'treasure',
            connectedNodes: ['nf-6'],
            description: 'A spring that runs red with iron. Or with worse.',
        },
        {
            id: 'nf-5',
            x: 260,
            y: 240,
            label: 'Wolf’s Den',
            type: 'encounter',
            connectedNodes: ['nf-7'],
            description: 'A reek of wet fur. Bone splinters at the threshold.',
        },
        {
            id: 'nf-6',
            x: 150,
            y: 170,
            label: 'Pilgrim’s Cairn',
            type: 'quest',
            connectedNodes: ['nf-8'],
            description: 'A cairn raised by some earlier pilgrim. Names worn flat.',
        },
        {
            id: 'nf-7',
            x: 290,
            y: 160,
            label: 'Brokenstag',
            type: 'boss',
            connectedNodes: ['nf-9'],
            description: 'Antlered shape in the gloom. It does not move.',
        },
        {
            id: 'nf-8',
            x: 90,
            y: 90,
            label: 'Cold Hearth',
            type: 'rest',
            connectedNodes: ['nf-10'],
            description: 'A cold hearth in a roofless house. Sleep light.',
        },
        {
            id: 'nf-9',
            x: 220,
            y: 80,
            label: 'Black Hollow',
            type: 'encounter',
            connectedNodes: ['nf-10'],
            description: 'A hollow the locals will not name in daylight.',
        },
        {
            id: 'nf-10',
            x: 310,
            y: 50,
            label: 'The Causeway',
            type: 'boss',
            connectedNodes: [],
            description: 'A causeway leading north. The way out, if there is one.',
        },
        // ── Districts (nf-11..nf-25) — positions placed off the engine's
        // location grid; kind + edges come from the engine. Labels/blurbs
        // authored in the game's voice. ──
        { id: 'nf-11', x: 178, y: 280, label: 'Ranger’s Rest', description: 'An old ranger’s lean-to, still dry beneath the boughs.' },
        { id: 'nf-12', x: 67,  y: 280, label: 'Thornbrake', description: 'A snarl of black thorn that grabs at the careless.' },
        { id: 'nf-13', x: 104, y: 280, label: 'The Mossbeds', description: 'Soft green hummocks, thick with useful growth.' },
        { id: 'nf-14', x: 141, y: 285, label: 'Hermit’s Hollow', description: 'A reed hut tucked where the pines lean close.' },
        { id: 'nf-15', x: 141, y: 140, label: 'Bramble Snare', description: 'The undergrowth here keeps teeth of its own.' },
        { id: 'nf-16', x: 200, y: 130, label: 'Hunter’s Cache', description: 'A waxed bundle wedged in a hollow trunk.' },
        { id: 'nf-17', x: 245, y: 120, label: 'The Standing Stones', description: 'Grey monoliths older than the forest. They watch.' },
        { id: 'nf-18', x: 195, y: 270, label: 'Glen Market', description: 'A handful of stalls where two trails cross.' },
        { id: 'nf-19', x: 235, y: 285, label: 'Shadewood', description: 'The canopy closes; something stirs against the dark.' },
        { id: 'nf-20', x: 67,  y: 350, label: 'Sunken Reliquary', description: 'A stone box half-swallowed by the loam.' },
        { id: 'nf-21', x: 110, y: 360, label: 'Echo Stone', description: 'Speak here and the forest answers — late, and wrong.' },
        { id: 'nf-22', x: 255, y: 205, label: 'Moonbell Glade', description: 'Pale flowers that open only after dusk.' },
        { id: 'nf-23', x: 290, y: 200, label: 'Wanderer’s Fire', description: 'A philosopher tends a small fire, glad of company.' },
        { id: 'nf-24', x: 300, y: 270, label: 'Keeper’s Cairn', description: 'A watch-cairn where the old rangers slept in turns.' },
        { id: 'nf-25', x: 335, y: 285, label: 'Mist Pools', description: 'Cold pools that breathe a fog to turn you around.' },
    ],
};
