import type { MapLayout } from './types';

export const northernForestLayout: MapLayout = {
    mapId: 'northern-forest',
    continent: 'CONTINENT · COASTAL',
    region: 'Northern Forest',
    regionProgress: 'Map ii of ii · 9 paths remain',
    nodes: [
        {
            id: 'nf-1',
            x: 60,
            y: 360,
            label: 'Forest Edge',
            type: 'rest',
            connectedNodes: ['nf-2', 'nf-3'],
            description: 'Where the pines first taste the salt wind.',
        },
        {
            id: 'nf-2',
            x: 140,
            y: 300,
            label: 'Foxglove Hollow',
            type: 'gather',
            connectedNodes: ['nf-4'],
            description: 'A hollow thick with foxglove and adder-tongue.',
        },
        {
            id: 'nf-3',
            x: 220,
            y: 320,
            label: 'Hangman’s Oak',
            type: 'encounter',
            connectedNodes: ['nf-5'],
            description: 'An old oak. Old rope still bites into its bark.',
        },
        {
            id: 'nf-4',
            x: 80,
            y: 220,
            label: 'Iron Spring',
            type: 'treasure',
            connectedNodes: ['nf-6'],
            description: 'A spring that runs red with iron. Or with worse.',
        },
        {
            id: 'nf-5',
            x: 260,
            y: 240,
            label: 'Wolf’s Den',
            type: 'encounter',
            connectedNodes: ['nf-7'],
            description: 'A reek of wet fur. Bone splinters at the threshold.',
        },
        {
            id: 'nf-6',
            x: 150,
            y: 170,
            label: 'Pilgrim’s Cairn',
            type: 'quest',
            connectedNodes: ['nf-8'],
            description: 'A cairn raised by some earlier pilgrim. Names worn flat.',
        },
        {
            id: 'nf-7',
            x: 290,
            y: 160,
            label: 'Brokenstag',
            type: 'boss',
            connectedNodes: ['nf-9'],
            description: 'Antlered shape in the gloom. It does not move.',
        },
        {
            id: 'nf-8',
            x: 90,
            y: 90,
            label: 'Cold Hearth',
            type: 'rest',
            connectedNodes: ['nf-10'],
            description: 'A cold hearth in a roofless house. Sleep light.',
        },
        {
            id: 'nf-9',
            x: 220,
            y: 80,
            label: 'Black Hollow',
            type: 'encounter',
            connectedNodes: ['nf-10'],
            description: 'A hollow the locals will not name in daylight.',
        },
        {
            id: 'nf-10',
            x: 310,
            y: 50,
            label: 'The Causeway',
            type: 'boss',
            connectedNodes: [],
            description: 'A causeway leading north. The way out, if there is one.',
        },
    ],
};
