/**
 * Dev-only "loot a real rarity drop" injection (Phase 136).
 *
 * POPULATE and ADD ITEM BY ID hand out registry-backed gear: common /
 * base equipment, unique relics, and consumables. But uncommon and
 * rare equipment are generated by the engine at *drop time* by rolling
 * modifiers onto a base template. These buttons roll REAL drops at a
 * requested rarity straight from engine truth (`dropItem`), so the
 * resulting item carries genuine rolled modifiers.
 *
 * Affix / modifier counts (mechanics 0.22.x — `MODS_PER_RARITY`):
 *
 * - common   → 0 modifiers
 * - uncommon → 1 modifier
 * - rare     → 2 modifiers
 * - unique   → 3 *fixed* modifiers (the template's `fixedModIds`,
 *              rolled to good values for the player's level — the same
 *              three every time for a given unique relic)
 *
 * The engine rolls exactly `MODS_PER_RARITY[rarity]` *procedural* base
 * modifiers. Some base templates additionally carry *baked* prefix /
 * suffix affixes (`template.prefixId` / `template.suffixId`) that the
 * factory force-pins on top of the procedural roll, which would push
 * the modifier count above the rarity's target (e.g. a common with a
 * baked prefix lands at 1, not 0). Those baked affixes can't be
 * suppressed through `dropItem`, so for common / uncommon / rare we
 * draw only from templates with no baked affixes — the procedural roll
 * then lands on the exact target. We still verify the realised count and
 * skip any straggler, so a drop is never reported at the wrong rarity.
 * Uniques source from `uniqueTemplates` (their three fixed mods are the
 * point, so the baked-affix exclusion doesn't apply).
 *
 * (Forcing exact counts mobile-side is a stopgap; the engine should be
 * able to drop an item at an exact modifier count for a rarity without
 * the caller hand-filtering templates — filed upstream against
 * axiomancer-mechanics.)
 *
 * No fake local minting: the only rarity input is the engine's own
 * `rarity` parameter on `dropItem`. We pick a level-eligible base
 * template and try a bounded number of templates until one rolls
 * cleanly, so a single unlucky template never strands the drop and the
 * loop is never unbounded.
 *
 * Component mount is `isDevToolsEnabled()`-guarded; production never
 * reaches this.
 */

import {
    dropItem,
    equipmentTemplates,
    uniqueTemplates,
    type EquipmentTemplate,
    type UniqueItemTemplate,
    type Equipment,
} from 'axiomancer-mechanics';

import type { AppStore } from '@/state/store';

/** Procedural drop rarities this dev tool can request. */
export type LootRarity = 'common' | 'uncommon' | 'rare' | 'unique';

/**
 * Target modifier count per rarity — mirrors the engine's
 * `MODS_PER_RARITY` (mechanics 0.22.x). Common carries no modifiers,
 * uncommon one, rare two; uniques carry their three fixed modifiers.
 */
const MODS_PER_RARITY: Record<LootRarity, number> = {
    common: 0,
    uncommon: 1,
    rare: 2,
    unique: 3,
};

export interface LootRarityResult {
    /** True when a real drop was generated and pushed to inventory. */
    added: boolean;
    /** The requested rarity. */
    rarity: LootRarity;
    /** Generated item display name, or null on failure. */
    name: string | null;
    /** Count of rolled modifiers, or null on failure. */
    affixCount: number | null;
    /** Human-readable reason when `added` is false. */
    reason: string | null;
}

/** Bounded attempt cap — never an unbounded retry loop (brief §40). */
const MAX_ATTEMPTS = 16;

/**
 * Count rolled modifiers on an engine `Equipment` for reporting and
 * exact-count enforcement. This engine version records every rolled
 * modifier (procedural base mods, baked affixes, and a unique's fixed
 * mods) in `rolledMods`, so `rolledMods.length` is the truthful count.
 * Falls back to the structured prefix/suffix fields for older/forward
 * engine shapes that predate `rolledMods`.
 */
export function countAffixes(item: Equipment): number {
    if (item.rolledMods && item.rolledMods.length > 0) {
        return item.rolledMods.length;
    }
    const hasPrefix = Boolean(item.prefixId ?? item.prefixName);
    const hasSuffix = Boolean(item.suffixId ?? item.suffixName);
    return (hasPrefix ? 1 : 0) + (hasSuffix ? 1 : 0);
}

/** A template carries baked affixes when it pins a prefix or suffix the
 * factory will force on top of the procedural roll. */
function hasBakedAffix(template: EquipmentTemplate): boolean {
    return Boolean(template.prefixId ?? template.suffixId);
}

/** Shuffle-free deterministic-enough rotation: start at a random index
 * and walk the eligible pool, so repeated presses vary the base item
 * without an unbounded loop. */
function* rotate<T>(pool: readonly T[]): Generator<T> {
    if (pool.length === 0) return;
    const start = Math.floor(Math.random() * pool.length);
    for (let i = 0; i < pool.length; i++) {
        yield pool[(start + i) % pool.length];
    }
}

/** A fresh inventory-unique instance id so repeated dev drops of the
 * same base template never collapse into a single stacked row. */
function instanceId(item: Equipment, store: AppStore, rarity: LootRarity, attempt: number): string {
    const len = store.getState().player.inventory.length;
    return `${item.id}__devloot_${rarity}_${len}_${attempt}`;
}

/**
 * Generate one real drop at the requested rarity and push it into the
 * player's inventory. Picks a level-eligible base template, rolls it via
 * the engine `dropItem` at the explicit rarity, enforces the exact
 * modifier count for that rarity, and reports the generated item's name
 * + modifier count. Never throws; a failure to generate returns a
 * graceful `added: false` with a visible reason.
 */
export function lootRarityItem(
    store: AppStore,
    rarity: LootRarity,
): LootRarityResult {
    try {
        const state = store.getState();
        const addItem = state.addItem;
        const playerLevel = state.player?.level ?? 1;
        const targetMods = MODS_PER_RARITY[rarity];

        // Uniques source from the unique registry (their three fixed
        // mods are the point); every other rarity rolls a procedural
        // base, drawing only from templates with no baked affixes so the
        // realised modifier count lands on the rarity's exact target.
        const eligible: readonly (EquipmentTemplate | UniqueItemTemplate)[] =
            rarity === 'unique'
                ? uniqueTemplates.filter((t) => t.requiredLevel <= playerLevel)
                : equipmentTemplates.filter(
                      (t) => t.requiredLevel <= playerLevel && !hasBakedAffix(t),
                  );

        if (eligible.length === 0) {
            return {
                added: false,
                rarity,
                name: null,
                affixCount: null,
                reason:
                    rarity === 'unique'
                        ? `no unique relic is available at level ${playerLevel}`
                        : `no level-eligible base template at level ${playerLevel}`,
            };
        }

        let attempts = 0;
        for (const tpl of rotate(eligible)) {
            if (attempts >= MAX_ATTEMPTS) break;
            attempts++;
            try {
                const item = dropItem(tpl.id, playerLevel, rarity) as Equipment;
                // Defensive: skip any drop whose realised modifier count
                // doesn't match the rarity's target (e.g. an unforeseen
                // baked affix), so we never report a wrong-rarity drop.
                if (countAffixes(item) !== targetMods) continue;

                const instancedItem: Equipment = {
                    ...item,
                    id: instanceId(item, store, rarity, attempts),
                    rarity,
                };
                addItem(instancedItem);
                return {
                    added: true,
                    rarity,
                    name: instancedItem.name,
                    affixCount: countAffixes(instancedItem),
                    reason: null,
                };
            } catch {
                // This base template could not roll the requested rarity
                // (e.g. too few eligible mods for its slot). Try the next
                // one within the bounded cap.
            }
        }

        return {
            added: false,
            rarity,
            name: null,
            affixCount: null,
            reason: `could not generate a ${rarity} drop after ${attempts} attempts`,
        };
    } catch (error) {
        console.error(`Failed to loot ${rarity} item:`, error);
        return {
            added: false,
            rarity,
            name: null,
            affixCount: null,
            reason: 'loot failed — see console',
        };
    }
}

/** Convenience wrapper — loot one real common drop (0 modifiers). */
export function lootCommonItemAction(store: AppStore): LootRarityResult {
    return lootRarityItem(store, 'common');
}

/** Convenience wrapper — loot one real uncommon drop (1 modifier). */
export function lootUncommonItemAction(store: AppStore): LootRarityResult {
    return lootRarityItem(store, 'uncommon');
}

/** Convenience wrapper — loot one real rare drop (2 modifiers). */
export function lootRareItemAction(store: AppStore): LootRarityResult {
    return lootRarityItem(store, 'rare');
}

/** Convenience wrapper — loot one unique relic (3 fixed modifiers). */
export function lootUniqueItemAction(store: AppStore): LootRarityResult {
    return lootRarityItem(store, 'unique');
}
